### ISSUE TITLE
'DropPath' object has no attribute 'scale_by_keep'

### ISSUE THREAD

**Issue by HoangTienDuc** [jahongir7174/EfficientNetV2#6]
#### HARDWARE
- Ubuntu 18.04
- Torch 1.7.0a0+7036e91
- Torch vision 0.8.0a0

Hi, @jahongir7174 Thank you for your awesome work.

I tried to run a test on your pre-trained model. However, It seems that the pre-trained model gives me an error. 
Could you please help me to solve this problem?
```
Number of parameters: 21458488
     acc@1     acc@5:   0%|                                                                                                                                                          | 0/48 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "main.py", line 227, in <module>
    main()
  File "main.py", line 223, in main
    test()
  File "main.py", line 171, in test
    loss, acc1, acc5 = batch(images, target, model, criterion)
  File "main.py", line 43, in batch
    output = model(images)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/ws/EfficientNetV2/nets/nn.py", line 164, in forward
    x = self.p1(x)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/ws/EfficientNetV2/nets/nn.py", line 69, in forward
    return x + self.res(x) if self.add else self.res(x)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/timm/models/layers/drop.py", line 164, in forward
    return drop_path(x, self.drop_prob, self.training, self.scale_by_keep)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 779, in __getattr__
    type(self).__name__, name))
torch.nn.modules.module.ModuleAttributeError: 'DropPath' object has no attribute 'scale_by_keep'
```

I also create a script to test your model on a single image, got the same problem too.
```
import torch
from torchvision import transforms
from PIL import Image


model = torch.load('weights/best.pt', map_location='cuda')['model'].float()
with torch.no_grad():
    model.eval()  

image = Image.open("/ws/dataset/hamxe_dataset/data_fake/data_Fake/data/mau/bike/EtzcWfSbQS.jpg")
normalize = transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])

transform_norm = transforms.Compose([transforms.Resize(384),
                                          transforms.CenterCrop(384),
                                          transforms.ToTensor(), normalize])
img_normalized = transform_norm(image).float()
img_normalized = img_normalized.unsqueeze_(0)
img_normalized = img_normalized.cuda()

with torch.cuda.amp.autocast():
    output = model(img_normalized)

print(output)
```

**Comment by jahongir7174** [comment]
@HoangTienDuc Thanks for your interest. The issue is related to `timm` package. I think you are using the latest version of `timm`, please use `pip install timm==0.4.12`
